apiVersion: v1
kind: Secret
metadata:
  name: twenty-secrets
  namespace: twentycrm
type: Opaque
stringData:
  APP_SECRET: "my_super_secret_change_in_production"
  PG_DATABASE_PASSWORD: "twenty_db_password"
  PG_DATABASE_USER: "twenty_app_user"
