apiVersion: v1
kind: Service
metadata:
  name: twenty-server
  namespace: twentycrm
spec:
  selector:
    app: twenty-server
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30020
